development:
  adapter: mysql2
  username: test
  password: test
  encoding: utf8
  reconnect: false
  database: osexchange_dev
  pool: 5

test:
  adapter: mysql2
  username: test
  password: test
  encoding: utf8
  reconnect: false
  database: osexchange_tst
  pool: 5

production:
  adapter: mysql2
  username: test
  password: test
  encoding: utf8
  reconnect: false
  pool: 5
  database: osexchange_prd
